# websites.conf - Configuration File for SSL Certificate Expiration Checker
# this file was created as template and should be edited to add your own websites

# Format: WEBSITE_URL [WARNING_DAYS] [ERROR_DAYS]
# Lines starting with # are ignored

# Default thresholds will be used (30 days warning, 7 days error)
google.com
microsoft.com
apple.com

# Invalid websites for testing purposes:
wrong.domain.name. # Test with a wrong domain
https://www.not-existing.domain # Test with non-existing domain, but with 'https' and 'www'
invalid-domain.test 60 31 # Test with an invalid domain and custom thresholds
something_else # Test with a random string
expired-rsa-dv.ssl.com # Test with an expired certificate

# Custom thresholds
github.com 45 10
sap.com 365 14 # force to have [WARNING]
docker.com 365 200 # force to have [CRITICAL]

# Additional examples
example.com:8443 30 7 # with set port
expired-rsa-dv.ssl.com # expired certificate
www.google.com # Test with 'www'
https://google.com # Test with 'https'
https://www.google.com # Test with 'https' and 'www'
https://calendar.google.com/calendar # Test with a valid domain and path
